import type { Metadata } from "next";
import { Crete_Round, Work_Sans } from "next/font/google";
import { ChildProps } from "@/types";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "./globals.css";

const CreteRound = Crete_Round({
  weight: ['400'],
  variable: '--font-CreteRound',
  subsets: ['latin']
})
const WorkSans = Work_Sans({
  weight: ['500', '600'],
  subsets: ['latin'],
  variable: '--font-WorkSans'
})

export const metadata: Metadata = {
  title: "KhurDev",
  description: "Generated by create next app",
};

function RootLayout({ children }: ChildProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${CreteRound.variable} ${WorkSans.variable} overflow-x-hidden `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;